import React, { useEffect, useRef } from 'react';

interface LegalModalProps {
  type: 'terms' | 'privacy';
  onClose: () => void;
}

export const LegalModal: React.FC<LegalModalProps> = ({ type, onClose }) => {
  const closeBtnRef = useRef<HTMLButtonElement>(null);

  useEffect(() => {
    closeBtnRef.current?.focus();

    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') onClose();
    };

    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [onClose]);

  return (
    <div className="legal-modal-overlay" role="dialog" aria-modal="true" aria-labelledby="legal-modal-title">
      <div className="legal-modal-content animate-fade-in">
        <button ref={closeBtnRef} type="button" className="legal-close-btn" onClick={onClose} aria-label="Close legal modal">
          &times;
        </button>
        <h2 id="legal-modal-title">{type === 'terms' ? 'Terms & Conditions' : 'Privacy Policy'}</h2>

        <div className="legal-text">
          {type === 'terms' ? (
            <>
              <h3>1. Acceptance of Terms</h3>
              <p>By accessing and using Wheel Rush, you accept and agree to be bound by the terms and provision of this agreement.</p>

              <h3>2. Virtual Currency</h3>
              <p>The balance and currency used in Wheel Rush are purely virtual and carry absolutely no real-world monetary value. They cannot be exchanged, cashed out, or transferred.</p>

              <h3>3. Fair Play & Security</h3>
              <p>We leverage Server-Side generation for spin outcomes. Any attempt to tamper with client-side code, use automated scripts, or exploit the platform will result in immediate account termination.</p>

              <h3>4. Account Responsibility</h3>
              <p>You are responsible for maintaining the confidentiality of your account credentials. Wheel Rush is not liable for any losses incurred due to unauthorized account access.</p>
            </>
          ) : (
            <>
              <p><strong>Last updated: June 19, 2026</strong></p>
              <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
              <p>We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

              <h3>Interpretation and Definitions</h3>
              <h4>Interpretation</h4>
              <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

              <h4>Definitions</h4>
              <p>For the purposes of this Privacy Policy:</p>
              <ul>
                <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                <li><strong>Company</strong> refers to wheel rush.</li>
                <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website.</li>
                <li><strong>Country</strong> refers to: Nigeria</li>
                <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                <li><strong>Service</strong> refers to the Website.</li>
                <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                <li><strong>Website</strong> refers to wheel rush, accessible from https://wheelrush.fun/.</li>
                <li><strong>You</strong> means the individual accessing or using the Service.</li>
              </ul>

              <h3>Collecting and Using Your Personal Data</h3>
              <h4>Types of Data Collected</h4>
              <h5>Personal Data</h5>
              <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: Email address, Usage Data.</p>

              <h4>Usage Data</h4>
              <p>Usage Data is collected automatically when using the Service. This may include Your Device's IP address, browser type, browser version, and pages visited.</p>

              <h4>Tracking Technologies and Cookies</h4>
              <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information.</p>

              <h3>Use of Your Personal Data</h3>
              <p>The Company may use Personal Data for the following purposes:</p>
              <ul>
                <li>To provide and maintain our Service.</li>
                <li>To manage Your Account.</li>
                <li>To contact You by email regarding updates or security communications.</li>
                <li>To provide You with news and special offers.</li>
                <li>To manage Your requests.</li>
              </ul>

              <h3>Retention of Your Personal Data</h3>
              <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. Account information is typically retained for the duration of your account relationship plus up to 24 months.</p>

              <h3>Transfer of Your Personal Data</h3>
              <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located.</p>

              <h3>Delete Your Personal Data</h3>
              <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>

              <h3>Security of Your Personal Data</h3>
              <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet is 100% secure.</p>

              <h3>Children's Privacy</h3>
              <p>Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16.</p>

              <h3>Changes to this Privacy Policy</h3>
              <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>

              <h3>Contact Us</h3>
              <p>If you have any questions about this Privacy Policy, You can contact us:</p>
              <ul>
                <li>By email: collinstheegod@gmail.com</li>
              </ul>
            </>
          )}
        </div>
      </div>
    </div>
  );
};
